#!/bin/bash
#This just merges updates from a superproject (which has this project embedded
# in it as a subtree) into the current branch, and deletes the branch
# when it's done.

set -o errexit

if [[ $(git branch -a |grep origin/update) ]]; then
	echo "update from a non-local remote..."
	git pull
	git merge origin/update_from_superproject
else
	git merge update_from_superproject
fi

echo "Done merging. Delete update_from_superproject branch? (ctrl-c for no)"
read
if [[ $(git branch -a |grep origin/update) ]]; then
	git push origin :update_from_superproject
else
	git branch -d update_from_superproject
fi
